""" Static data for tests
"""

OANDA_SYMBOLS = ["OANDA:SPX500_USD", "OANDA:CN50_USD", "OANDA:SUGAR_USD", "OANDA:BCO_USD", "OANDA:IN50_USD",
                 "OANDA:NZD_USD", "OANDA:GBP_USD", "OANDA:XAG_USD", "OANDA:USB30Y_USD", "OANDA:USB10Y_USD",
                 "OANDA:WTICO_USD", "OANDA:EUR_USD", "OANDA:XPD_USD", "OANDA:USB02Y_USD", "OANDA:USB05Y_USD",
                 "OANDA:XPT_USD", "OANDA:XCU_USD", "OANDA:TWIX_USD", "OANDA:WHEAT_USD", "OANDA:NAS100_USD",
                 "OANDA:US2000_USD", "OANDA:JP225_USD", "OANDA:US30_USD", "OANDA:CORN_USD", "OANDA:XAU_USD",
                 "OANDA:AUD_USD", "OANDA:SOYBN_USD", "OANDA:NATGAS_USD"]
FXCM_SYMBOLS = ["FXCM:ETH/USD", "FXCM:XAG/USD", "FXCM:AUD/USD", "FXCM:BCH/USD", "FXCM:EUR/USD", "FXCM:LTC/USD",
                "FXCM:XAU/USD", "FXCM:BTC/USD", "FXCM:XRP/USD", "FXCM:NZD/USD", "FXCM:GBP/USD"]
FOREX_SYMBOLS = ["FOREX:401484300", "FOREX:401484301", "FOREX:401484302", "FOREX:401484303", "FOREX:401484304", 
                 "FOREX:401484314", "FOREX:401484315", "FOREX:401484316", "FOREX:401484317", "FOREX:401484320",
                 "FOREX:401484321", "FOREX:401484322", "FOREX:401484323", "FOREX:401484324", "FOREX:401484325"]
FXPIG_SYMBOLS = ["FXPIG:1", "FXPIG:2", "FXPIG:3", "FXPIG:4", "FXPIG:5", "FXPIG:6", "FXPIG:7", "FXPIG:8", "FXPIG:9",
                 "FXPIG:10"]
PEPPERSTONE_SYMBOLS = ["PEPPERSTONE:1", "PEPPERSTONE:2", "PEPPERSTONE:3", "PEPPERSTONE:4", "PEPPERSTONE:5",
                       "PEPPERSTONE:6", "PEPPERSTONE:7", "PEPPERSTONE:8", "PEPPERSTONE:9", "PEPPERSTONE:10"]
ICMTRADER_SYMBOLS = ["ICMTRADER:1", "ICMTRADER:2", "ICMTRADER:3", "ICMTRADER:4", "ICMTRADER:5", "ICMTRADER:6",
                     "ICMTRADER:7", "ICMTRADER:8", "ICMTRADER:9", "ICMTRADER:10"]
FXPRO_SYMBOLS = ["FXPRO:1", "FXPRO:2", "FXPRO:3", "FXPRO:4", "FXPRO:5", "FXPRO:6", "FXPRO:7", "FXPRO:8", "FXPRO:9",
                 "FXPRO:10"]
PEPPERSTONEUK_SYMBOLS = ["PEPPERSTONEUK:1", "PEPPERSTONEUK:2", "PEPPERSTONEUK:3", "PEPPERSTONEUK:4", "PEPPERSTONEUK:5",
                         "PEPPERSTONEUK:6", "PEPPERSTONEUK:7", "PEPPERSTONEUK:8", "PEPPERSTONEUK:9", "PEPPERSTONEUK:10"]
IC_MARKETS_SYMBOL = ["IC MARKETS:1", "IC MARKETS:2", "IC MARKETS:3", "IC MARKETS:4", "IC MARKETS:5", "IC MARKETS:6",
                     "IC MARKETS:7", "IC MARKETS:8", "IC MARKETS:9", "IC MARKETS:10"]

SYMBOLS = {'oanda': OANDA_SYMBOLS,
           'fxcm': FXCM_SYMBOLS,
           'forex.com': FOREX_SYMBOLS,
           'fxpig': FXPIG_SYMBOLS,
           'pepperstone': PEPPERSTONE_SYMBOLS,
           'icmtrader': ICMTRADER_SYMBOLS,
           'fxpro': FXPRO_SYMBOLS,
           'pepperstoneuk': PEPPERSTONEUK_SYMBOLS,
           'ic markets': IC_MARKETS_SYMBOL}
